export default function robots() {
    return {
      rules: [
        {
          userAgent: '*',
          allow: '/',
          disallow: [
            "/corporate/",
            "/real-estate/",
            "/ru/*",
            "/ch/*",
            "/services/30",
            "/services/31",
            "/services/32",
            "/services/45",
            "/services/33",
            "/services/66",
            "/services/68",
            "/services/69",
            "/services/70",
            "/services/71",
            "/services/72",
            "/services/73",
            "/services/35",
            "/services/36",
            "/services/37",
            "/services/38",
            "/services/39",
            "/services/41",
            "/services/74",
            "/services/75",
            "/services/59",
            "/services/60",
            "/services/61",
            "/services/63",
            "/services/64",
            "/services/65",
            "/services/46",
            "/services/47",
            "/services/48",
            "/services/49",
            "/services/50",
            "/services/51",
            "/services/44",
            "/services/52",
            "/services/54",
            "/services/55",
            "/services/56",
            "/services/57",
            "/ar/services/30",
            "/ar/services/31",
            "/ar/services/32",
            "/ar/services/45",
            "/ar/services/33",
            "/ar/services/66",
            "/ar/services/68",
            "/ar/services/69",
            "/ar/services/70",
            "/ar/services/71",
            "/ar/services/72",
            "/ar/services/73",
            "/ar/services/35",
            "/ar/services/36",
            "/ar/services/37",
            "/ar/services/38",
            "/ar/services/39",
            "/ar/services/41",
            "/ar/services/74",
            "/ar/services/75",
            "/ar/services/59",
            "/ar/services/60",
            "/ar/services/61",
            "/ar/services/63",
            "/ar/services/64",
            "/ar/services/65",
            "/ar/services/46",
            "/ar/services/47",
            "/ar/services/48",
            "/ar/services/49",
            "/ar/services/50",
            "/ar/services/51",
            "/ar/services/44",
            "/ar/services/52",
            "/ar/services/54",
            "/ar/services/55",
            "/ar/services/56",
            "/ar/services/57",
            "/team/4",
            "/team/41",
            "/team/39",
            "/team/80",
            "/team/35",
            "/team/38",
            "/team/48",
            "/team/26",
            "/team/49",
            "/team/50",
            "/team/40",
            "/team/21",
            "/team/51",
            "/team/3",
            "/team/42",
            "/team/70",
            "/team/24",
            "/team/72",
            "/team/25",
            "/team/43",
            "/team/22",
            "/team/23",
            "/team/71",
            "/team/55",
            "/team/91",
            "/team/47",
            "/team/20",
            "/team/19",
            "/team/74",
            "/team/29",
            "/team/73",
            "/team/32",
            "/team/75",
            "/team/58",
            "/team/76",
            "/team/6",
            "/team/36",
            "/team/57",
            "/team/59",
            "/team/79",
            "/team/81",
            "/team/87",
            "/team/67",
            "/team/60",
            "/team/37",
            "/team/61",
            "/team/62",
            "/team/88",
            "/team/63",
            "/team/78",
            "/team/89",
            "/team/34",
            "/team/82",
            "/team/68",
            "/team/95",
            "/ar/team/4",
            "/ar/team/41",
            "/ar/team/39",
            "/ar/team/80",
            "/ar/team/35",
            "/ar/team/38",
            "/ar/team/48",
            "/ar/team/26",
            "/ar/team/49",
            "/ar/team/50",
            "/ar/team/40",
            "/ar/team/21",
            "/ar/team/51",
            "/ar/team/3",
            "/ar/team/42",
            "/ar/team/70",
            "/ar/team/24",
            "/ar/team/72",
            "/ar/team/25",
            "/ar/team/43",
            "/ar/team/22",
            "/ar/team/23",
            "/ar/team/71",
            "/ar/team/55",
            "/ar/team/91",
            "/ar/team/47",
            "/ar/team/20",
            "/ar/team/19",
            "/ar/team/74",
            "/ar/team/29",
            "/ar/team/73",
            "/ar/team/32",
            "/ar/team/75",
            "/ar/team/58",
            "/ar/team/76",
            "/ar/team/6",
            "/ar/team/36",
            "/ar/team/57",
            "/ar/team/59",
            "/ar/team/79",
            "/ar/team/81",
            "/ar/team/87",
            "/ar/team/67",
            "/ar/team/60",
            "/ar/team/37",
            "/ar/team/61",
            "/ar/team/62",
            "/ar/team/88",
            "/ar/team/63",
            "/ar/team/78",
            "/ar/team/89",
            "/ar/team/34",
            "/ar/team/82",
            "/ar/team/68",
            "/ar/team/95"
          ],
        },
        {
          userAgent: 'Googlebot',
          allow: '/',
        //   disallow: [
        //     '/services/30',
        //     '/services/31',
        //     '/services/32',
        //     '/services/45',
        //     '/services/33',
        //     '/services/66',
        //     '/services/67',
        //     '/services/68',
        //     '/services/69',
        //     '/services/70',
        //     '/services/71',
        //     '/services/72',
        //     '/services/73',
        //     '/services/35',
        //     '/services/36',
        //     '/services/37',
        //     '/services/38',
        //     '/services/39',
        //     '/services/41',
        //     '/services/42',
        //     '/services/43',
        //     '/services/74',
        //     '/services/75',
        //     '/services/59',
        //     '/services/60',
        //     '/services/61',
        //     '/services/62',
        //     '/services/63',
        //     '/services/64',
        //     '/services/65',
        //     '/services/46',
        //     '/services/47',
        //     '/services/48',
        //     '/services/49',
        //     '/services/50',
        //     '/services/51',
        //     '/services/44',
        //     '/services/52',
        //     '/services/53',
        //     '/services/54',
        //     '/services/55',
        //     '/services/56',
        //     '/services/57',
        //     '/services/58',
        //     '/services/34',
        //     '/team/4',
        //     '/team/41',
        //     '/team/35',
        //     '/team/39',
        //     '/team/80',
        //     '/team/31',
        //     '/team/38',
        //     '/team/48',
        //     '/team/26',
        //     '/team/49',
        //     '/team/50',
        //     '/team/40',
        //     '/team/21',
        //     '/team/51',
        //     '/team/3',
        //     '/team/42',
        //     '/team/52',
        //     '/team/70',
        //     '/team/24',
        //     '/team/72',
        //     '/team/25',
        //     '/team/43',
        //     '/team/22',
        //     '/team/23',
        //     '/team/71',
        //     '/team/55',
        //     '/team/91',
        //     '/team/47',
        //     '/team/20',
        //     '/team/19',
        //     '/team/74',
        //     '/team/29',
        //     '/team/73',
        //     '/team/32',
        //     '/team/75',
        //     '/team/6',
        //     '/team/36',
        //     '/team/58',
        //     '/team/76',
        //     '/team/69',
        //     '/team/57',
        //     '/team/59',
        //     '/team/79',
        //     '/team/81',
        //     '/team/87',
        //     '/team/67',
        //     '/team/60',
        //     '/team/37',
        //     '/team/61',
        //     '/team/62',
        //     '/team/88',
        //     '/team/63',
        //     '/team/78',
        //     '/team/89',
        //     '/team/34',
        //     '/team/82',
        //     '/team/68',
        //     '/team/95',
        //   ],
        },
        // {
        //   userAgent: '*',
        //   disallow: [
        //     '/services/30',
        //     '/services/31',
        //     '/services/32',
        //     '/services/45',
        //     '/services/33',
        //     '/services/66',
        //     '/services/67',
        //     '/services/68',
        //     '/services/69',
        //     '/services/70',
        //     '/services/71',
        //     '/services/72',
        //     '/services/73',
        //     '/services/35',
        //     '/services/36',
        //     '/services/37',
        //     '/services/38',
        //     '/services/39',
        //     '/services/41',
        //     '/services/42',
        //     '/services/43',
        //     '/services/74',
        //     '/services/75',
        //     '/services/59',
        //     '/services/60',
        //     '/services/61',
        //     '/services/62',
        //     '/services/63',
        //     '/services/64',
        //     '/services/65',
        //     '/services/46',
        //     '/services/47',
        //     '/services/48',
        //     '/services/49',
        //     '/services/50',
        //     '/services/51',
        //     '/services/44',
        //     '/services/52',
        //     '/services/53',
        //     '/services/54',
        //     '/services/55',
        //     '/services/56',
        //     '/services/57',
        //     '/services/58',
        //     '/services/34',
        //     '/team/4',
        //     '/team/41',
        //     '/team/35',
        //     '/team/39',
        //     '/team/80',
        //     '/team/31',
        //     '/team/38',
        //     '/team/48',
        //     '/team/26',
        //     '/team/49',
        //     '/team/50',
        //     '/team/40',
        //     '/team/21',
        //     '/team/51',
        //     '/team/3',
        //     '/team/42',
        //     '/team/52',
        //     '/team/70',
        //     '/team/24',
        //     '/team/72',
        //     '/team/25',
        //     '/team/43',
        //     '/team/22',
        //     '/team/23',
        //     '/team/71',
        //     '/team/55',
        //     '/team/91',
        //     '/team/47',
        //     '/team/20',
        //     '/team/19',
        //     '/team/74',
        //     '/team/29',
        //     '/team/73',
        //     '/team/32',
        //     '/team/75',
        //     '/team/6',
        //     '/team/36',
        //     '/team/58',
        //     '/team/76',
        //     '/team/69',
        //     '/team/57',
        //     '/team/59',
        //     '/team/79',
        //     '/team/81',
        //     '/team/87',
        //     '/team/67',
        //     '/team/60',
        //     '/team/37',
        //     '/team/61',
        //     '/team/62',
        //     '/team/88',
        //     '/team/63',
        //     '/team/78',
        //     '/team/89',
        //     '/team/34',
        //     '/team/82',
        //     '/team/68',
        //     '/team/95',
        //   ],
        // },
      ],
      sitemap: 'https://www.raalc.ae/sitemap.xml',
    };
  }  