export default function sitemap() {
    return [
      { url: 'https://www.raalc.ae/', lastModified: new Date() },
      { url: 'https://www.raalc.ae/about', lastModified: new Date() },
      { url: 'https://www.raalc.ae/team', lastModified: new Date() },
      { url: 'https://www.raalc.ae/news', lastModified: new Date() },
      { url: 'https://www.raalc.ae/events', lastModified: new Date() },
      { url: 'https://www.raalc.ae/gallery', lastModified: new Date() },
      { url: 'https://www.raalc.ae/contact', lastModified: new Date() },
      { url: 'https://www.raalc.ae/services/holding-company-setup', lastModified: new Date() },
      { url: 'https://www.raalc.ae/services/corporate-governance-review-and-advisory', lastModified: new Date() },
      { url: 'https://www.raalc.ae/services/partnership-and-shareholder-agreements', lastModified: new Date() },
      { url: 'https://www.raalc.ae/services/business-structuring-services', lastModified: new Date() },
      { url: 'https://www.raalc.ae/services/regulatory-compliance', lastModified: new Date() },
      { url: 'https://www.raalc.ae/services/corporate-compliance-services', lastModified: new Date() },
      { url: 'https://www.raalc.ae/services/compliance-audits-and-reviews', lastModified: new Date() },
      { url: 'https://www.raalc.ae/services/regulatory-filings-and-reporting', lastModified: new Date() },
      { url: 'https://www.raalc.ae/services/ethics-and-whistleblower-programs', lastModified: new Date() },
      { url: 'https://www.raalc.ae/services/compliance-monitoring-and-remediation', lastModified: new Date() },
      { url: 'https://www.raalc.ae/services/data-privacy-and-security-compliance', lastModified: new Date() },
      { url: 'https://www.raalc.ae/services/intellectual-property-lawyer-in-dubai', lastModified: new Date() },
      { url: 'https://www.raalc.ae/services/corporate-intellectual-property-ip-services', lastModified: new Date() },
      { url: 'https://www.raalc.ae/services/legal-and-financial-services-for-intellectual-property-ip-of-individuals', lastModified: new Date() },
      { url: 'https://www.raalc.ae/services/asset-tracing-services', lastModified: new Date() },
      { url: 'https://www.raalc.ae/services/legal-investigation-and-due-diligence', lastModified: new Date() },
      { url: 'https://www.raalc.ae/services/international-asset-tracing', lastModified: new Date() },
      { url: 'https://www.raalc.ae/services/legal-support-and-representation', lastModified: new Date() },
      { url: 'https://www.raalc.ae/services/workplace-policies-and-compliance', lastModified: new Date() },
      { url: 'https://www.raalc.ae/services/corporate-employment-and-labour-services', lastModified: new Date() },
      { url: 'https://www.raalc.ae/services/employment-contracts-and-agreements', lastModified: new Date() },
      { url: 'https://www.raalc.ae/services/employee-relations-and-dispute-resolution', lastModified: new Date() },
      { url: 'https://www.raalc.ae/services/employment-law-compliance-audits', lastModified: new Date() },
      { url: 'https://www.raalc.ae/services/compensation-and-benefits', lastModified: new Date() },
      { url: 'https://www.raalc.ae/services/immigration-and-work-permits', lastModified: new Date() },
      { url: 'https://www.raalc.ae/services/occupational-health-and-safety-ohs', lastModified: new Date() },
      { url: 'https://www.raalc.ae/services/insurance-compliance', lastModified: new Date() },
      { url: 'https://www.raalc.ae/services/real-estate-lawyers', lastModified: new Date() },
      { url: 'https://www.raalc.ae/services/construction', lastModified: new Date() },
      { url: 'https://www.raalc.ae/services/debt-collection-agency-in-dubai', lastModified: new Date() },
      { url: 'https://www.raalc.ae/services/business-restructuring-and-reorganization', lastModified: new Date() },
      { url: 'https://www.raalc.ae/services/corporate-bankruptcy-services', lastModified: new Date() },
      { url: 'https://www.raalc.ae/services/debt-restructuring-and-negotiation', lastModified: new Date() },
      { url: 'https://www.raalc.ae/services/insolvency-advisory', lastModified: new Date() },
      { url: 'https://www.raalc.ae/services/legal-representation-in-insolvency-proceedings', lastModified: new Date() },
      { url: 'https://www.raalc.ae/services/expertise-in-mainland-and-freezone-insolvency-laws', lastModified: new Date() },
      { url: 'https://www.raalc.ae/services/arbitration-mediation', lastModified: new Date() },
      { url: 'https://www.raalc.ae/services/banking-finance', lastModified: new Date() },
      { url: 'https://www.raalc.ae/services/maritime', lastModified: new Date() },
      { url: 'https://www.raalc.ae/services/difc', lastModified: new Date() },
      { url: 'https://www.raalc.ae/services/information-technology', lastModified: new Date() },
      { url: 'https://www.raalc.ae/services/aviation', lastModified: new Date() },
      { url: 'https://www.raalc.ae/services/medical-negligence', lastModified: new Date() },
      { url: 'https://www.raalc.ae/services/criminal', lastModified: new Date() },
      { url: 'https://www.raalc.ae/services/litigation-dispute-resolution', lastModified: new Date() },
    ];
  }
  